# Generated by Django 4.0.4 on 2022-07-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceld'), ('confirmed', 'Confirmed')], default='pending', max_length=12),
        ),
    ]
